import { Post } from './wordpress/types';

export const placeholderPosts: Post[] = [
  {
    id: '1',
    title: 'A Glimpse into the Urban Jungle',
    slug: 'urban-jungle',
    date: '2024-07-28T10:00:00',
    modified: '2024-07-28T10:00:00',
    excerpt: 'Exploring the vibrant and chaotic life of the city through my lens. This series captures the raw energy, the towering structures, and the quiet moments in between...',
    content: 'This is the full content for the urban jungle post. It would contain more details, anecdotes, and reflections on the photoshoot.',
    author: { node: { name: 'Cielito' } },
    featuredImage: { node: { id: 'img1', sourceUrl: 'https://picsum.photos/seed/urban/1200/800', altText: 'A bustling city street at dusk' } },
    categories: { edges: [{ node: { id: 'cat1', name: 'Street Photography', slug: 'street-photography' } }] },
  },
  {
    id: '2',
    title: 'Serenity in Nature: A Coastal Escape',
    slug: 'coastal-escape',
    date: '2024-07-22T14:30:00',
    modified: '2024-07-22T14:30:00',
    excerpt: 'Finding peace where the land meets the sea. These photographs are a tribute to the calming power of the ocean and the rugged beauty of the coastline...',
    content: 'Full content for the coastal escape post. More about the trip and the feeling of being by the ocean.',
    author: { node: { name: 'Cielito' } },
    featuredImage: { node: { id: 'img2', sourceUrl: 'https://picsum.photos/seed/coast/1200/800', altText: 'Waves crashing on a rocky shore' } },
    categories: { edges: [{ node: { id: 'cat2', name: 'Nature', slug: 'nature' } }] },
  },
  {
    id: '3',
    title: 'Portraits of Resilience',
    slug: 'portraits-of-resilience',
    date: '2024-07-15T09:00:00',
    modified: '2024-07-15T09:00:00',
    excerpt: 'A collection of portraits that tell a story of strength, character, and the human spirit. Each face has a unique story to tell...',
    content: 'Full content for the portraits post, with background on the subjects and the creative process.',
    author: { node: { name: 'Cielito' } },
    featuredImage: { node: { id: 'img3', sourceUrl: 'https://picsum.photos/seed/portraits/1200/800', altText: 'A powerful black and white portrait' } },
    categories: { edges: [{ node: { id: 'cat3', name: 'Portraits', slug: 'portraits' } }] },
  },
  {
    id: '4',
    title: 'The Art of the Everyday: Finding Beauty in the Mundane',
    slug: 'art-of-everyday',
    date: '2024-07-10T18:00:00',
    modified: '2024-07-10T18:00:00',
    excerpt: 'This series is a challenge to myself to find and capture beauty in ordinary objects and scenes. From a coffee cup to a rain-soaked street...',
    content: 'Full content for the art of the everyday post, discussing the philosophy behind the series.',
    author: { node: { name: 'Cielito' } },
    featuredImage: { node: { id: 'img4', sourceUrl: 'https://picsum.photos/seed/everyday/1200/800', altText: 'Sunlight streaming through a window onto a simple object' } },
    categories: { edges: [{ node: { id: 'cat4', name: 'Abstract', slug: 'abstract' } }] },
  },
];
